### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nishh** [Sytm/md5-commons#2]
Spigot version: 1.14.4 (git-Paper-167)
md5-commons version: 0.1.0 (latest)

Error: https://paste.ubuntu.com/p/ms3bBj8zKv/
Plugins: https://paste.ubuntu.com/p/mDKmwyd9Q2/

When this error happened just 1 player was online and was AFK.

**Comment by Sytm** [comment]
Was my waypoints plugin installed previously?

I am 99,9% sure it was and it looks like you now have removed it.

Either delete the player store or reinstall waypoints
